module.exports.descriptors = [
    'Charming',
    'Rustic',
    'Modern',
    'Cozy',
    'Luxury',
    'Spacious',
    'Silent',
    'Suburban',
    'Large',
    'Furnished',
    'Pet Friendly',
    'Downtown',
    'Rural',
    'Mountain View',
    'City View',
    'Ocean View',
    'High Ceilings',
    'Newly Renovated'
]

module.exports.places = [
    'Flat',
    'Apartment',
    'Cottage',
    'House',
    'Condo',
    'Loft',
    "Studio",
    "Townhouse",
    "Penthouse",
    "Duplex",
    "Bungalow",
    "Cabin",
    "Villa",
    "Mansion",
    "Chalet",
    "Farmhouse",
    "Ranch",
    "Mobile Home",
    "Tiny House",
    "Row House",
    "Brownstone",
    "Colonial",
    "Craftsman",
    "Treehouse",
    "Yurt",
    "Container Home",
    "Basement Apartment",
    "Micro-Apartment",
    "Duplex Penthouse"
]

